name: Build and Deploy Docs to Cloudflare Pages

on:
  push:
    branches:
      - master

concurrency:
    group: cloudflare-pages-deploy-docs-${{github.head_ref}}
    cancel-in-progress: true

jobs:
    build_to_cloudflare_pages:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        permissions:
          contents: read
          deployments: write
        steps:
            - name: Checkout to branch
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

            - name: Setup node
              uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
              with:
                  node-version: 18.x
                  cache: 'npm'

            - name: Cache dependencies
              id: cache-node-modules
              uses: actions/cache/restore@e12d46a63a90f2fae62d114769bbf2a179198b5c
              with:
                key: v1-docs-deps-{{ hashFiles("./utils-docs/package-lock.json") }}
                path: ./utils-docs/node_modules

            - name: Install npm dependencies
              if: steps.cache-node-modules.outputs.cache-hit == 'true'
              run: cd utils-docs && npm ci
              shell: bash
    
            - name: save_cache
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              uses: actions/cache/save@e12d46a63a90f2fae62d114769bbf2a179198b5c
              with:
                path: ./utils-docs/node_modules
                key: v1-docs-deps-{{ hashFiles("./utils-docs/package-lock.json") }}

            - name: Build docs
              run: cd utils-docs && npm run build

            - name: Publish Docs to Cloudflare Pages
              uses: "deriv-com/shared-actions/.github/actions/publish_to_pages_production@master"
              with:
                CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                project_name: deriv-utils
                output_dir: ./utils-docs/build
