name: Run Unit Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: "20.x"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npx vitest run --coverage.enabled --coverage.provider=v8 --coverage.reporter=json-summary --coverage.reporter=json
      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
